name: Type checking and linting

on:
  pull_request:
  push:
    branches:
      - 'main'

permissions:
  pull-requests: write

jobs:
  typing:
    name: Typechecking
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup python for test 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install tox and uv
        run: python -m pip install uv
      - name: Setup uv
        run: uv venv
      - name: Install tox-uv
        run: uv tool install tox --with tox-uv
      - name: Install tox-gh
        run: uv pip install tox-gh>=1.2
      - name: Run test suite
        run: uv tool run tox -e type
  linting:
    name: Linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup python for test 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install tox and uv
        run: python -m pip install uv
      - name: Setup uv
        run: uv venv
      - name: Install tox-uv
        run: uv tool install tox --with tox-uv
      - name: Install tox-gh
        run: uv pip install tox-gh>=1.2
      - name: Run test suite
        run: uv tool run tox -e lint
